version: '3.10'

services:
  frontend:
    build:
      dockerfile: ./Dockerfile
    container_name: next-frontend-app
    networks:
      - local-net
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:17.5-alpine3.22
    container_name: postgres-database
    networks:
      - local-net
    ports:
      - '5432:5432'
    volumes:
      - database-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: aptechka_database
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped

  nginx:
    image: nginx:1.28-alpine3.21
    container_name: nginx-proxy-server
    depends_on:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
      - '443:443'
    networks:
      - local-net
    restart: unless-stopped

networks:
  local-net:
    driver: bridge

volumes:
  database-storage:
